name: Recovery Build (Legacy)

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: 'Manifest URL (if want to use SSH keys, use git@github.com:XXXXX)'
        required: true
        default: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni'
      MANIFEST_BRANCH:
        description: 'Specify your Manifest Branch'
        required: true
        default: 'twrp-8.1'
      DEVICE_TREE_URL:
        description: 'Device Tree URL'
        required: true
        default: 'https://github.com/BiraruStudios/android_device_infinix_X650'
      DEVICE_TREE_BRANCH:
        description: 'Specify your Device Tree Branch'
        required: true
        default: 'test'
      DEVICE_PATH:
        description: 'Specify your Device Path'
        required: true
        default: 'device/infinix/Infinix_X650'
      COMMON_TREE_URL:
        description: 'Common Tree URL (if no common tree, leave blank)'
        required: false
      COMMON_PATH:
        description: 'Common Path (if no common tree, leave blank)'
        required: false
      DEVICE_NAME:
        description: 'Specify your Device Name'
        required: true
        default: 'Infinix_X650'
      MAKEFILE_NAME:
        description: 'Specify your Makefile Name'
        required: true
        default: 'omni_Infinix_X650'
      BUILD_TARGET:
        description: 'Specify your Build Target'
        required: true
        default: 'recovery'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: Display Run Parameters
      run: |
        echo "::group::User Environment Variables"
        echo "Manifest URL: ${{ github.event.inputs.MANIFEST_URL }}"
        echo "Manifest Branch: ${{ github.event.inputs.MANIFEST_BRANCH }}"
        echo "Device Tree URL: ${{ github.event.inputs.DEVICE_TREE_URL }}"
        echo "Device Tree Branch: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}"
        echo "Device Path: ${{ github.event.inputs.DEVICE_PATH }}"
        echo "Device Name: ${{ github.event.inputs.DEVICE_NAME }}"
        echo "Makefile Name: ${{ github.event.inputs.MAKEFILE_NAME }}"
        echo "Build Target: ${{ github.event.inputs.BUILD_TARGET }}.img"
        echo "::endgroup::"
 
    - name: Check Out
      uses: actions/checkout@v4

    - name: Cleanup Workspace
      run: |
        rm -rf workspace && mkdir workspace

    - name: Prepare the Build Environment
      run: |
        sudo apt update && sudo apt install -y \
            gperf gcc-10-multilib g++-10-multilib \
            lib32ncurses5-dev libgl1-mesa-dev xsltproc bc ccache \
            lib32readline-dev lzop pngcrush schedtool squashfs-tools \
            imagemagick qemu-user-static libstdc++-10-dev python2

    - name: Install OpenJDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Link Python2
      run: |
        sudo ln -sf /usr/bin/python2 /usr/bin/python

    - name: Setup SSH Keys
      if: ${{ startsWith(github.event.inputs.MANIFEST_URL, 'git@github.com') || 
          startsWith(github.event.inputs.DEVICE_TREE_URL, 'git@github.com') ||
          startsWith(github.event.inputs.COMMON_TREE_URL, 'git@github.com') }}
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: |
          ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install Repo Tool
      run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Initialize and Sync Repo
      run: |
        cd workspace
        repo init --depth=1 -u ${{ github.event.inputs.MANIFEST_URL }} -b ${{ github.event.inputs.MANIFEST_BRANCH }}
        repo sync -j$(nproc --all) --force-sync

    - name: Clone Device Tree
      run: |
        mkdir archive
        git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}
        git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} archive/
      working-directory: workspace

    - name: Get Device Tree Commit Hash
      run: |
        git rev-parse HEAD > device_tree_commit.txt
      working-directory: workspace

    - name: Clone Common Tree
      if: ${{ github.event.inputs.COMMON_TREE_URL && github.event.inputs.COMMON_PATH }}
      run: |
        git clone ${{ github.event.inputs.COMMON_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.COMMON_PATH }}
      working-directory: workspace

    - name: Sync Device Dependencies
      run: |
        bash ${GITHUB_WORKSPACE}/local_scripts/convert.sh ${{ github.event.inputs.DEVICE_PATH }}/omni.dependencies
        repo sync -j$(nproc --all)
      working-directory: workspace

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Build Recovery
      run: |
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch ${{ github.event.inputs.MAKEFILE_NAME }}-eng
        make ${{ github.event.inputs.BUILD_TARGET }}image -j$(nproc --all)
      working-directory: workspace

    - name: Set Build Date
      if: success()
      run: echo "BUILD_DATE=$(date '+%d %B %Y')" >> $GITHUB_ENV

    - name: Archive Source Code
      if: success()
      run: |
        zip -r dt-source.zip workspace/archive/
        tar -czvf dt-source.tar.gz workspace/archive/

    - name: Upload to Release
      if: success()
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ github.workspace }}/workspace/out/target/product/${{ inputs.DEVICE_NAME }}/${{ inputs.BUILD_TARGET }}.img
          ${{ github.workspace }}/workspace/out/target/product/${{ inputs.DEVICE_NAME }}/*installer*zip
          ${{ github.workspace }}/workspace/out/target/product/${{ inputs.DEVICE_NAME }}/ramdisk-recovery.*
          ${{ github.workspace }}/workspace/out/target/product/${{ inputs.DEVICE_NAME }}/vbmeta.*
          ${{ github.workspace }}/dt-source.zip
          ${{ github.workspace }}/dt-source.tar.gz
        name: Unofficial TWRP for ${{ inputs.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
          Build: ${{ inputs.MANIFEST_BRANCH }}
          Device: [Device Tree/Branch](${{ github.event.inputs.DEVICE_TREE_URL }}/tree/${{ github.event.inputs.DEVICE_TREE_BRANCH }})
          Commit: Most recent [commit](${{ github.event.inputs.DEVICE_TREE_URL }}/commit/$(cat ${{ github.workspace }}/workspace/device_tree_commit.txt)) during building.
        prerelease: true
