name: Testing

on:
  workflow_dispatch:

jobs:
  firststep:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check Out
      uses: actions/checkout@v4
    - name: Install Stuff
      run: |
        sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y coreutils
    - name: Make File
      run: |
        mkdir Testing
        ls -a
        cd Testing
        echo "E" > test.txt

  secondstep:
    if: github.event.repository.owner.id == github.event.sender.id
    needs: firststep
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check Out
      uses: actions/checkout@v4
    - name: Make File
      run: |
        ls -a
        cd Testing
        ls -a
        cat test.txt
