name: Testing

on:
  workflow_dispatch:
    inputs:
        MANIFEST_URL:
          description: 'Manifest URL (if want to use SSH keys, use git@github.com:XXXXX)'
          required: true
          default: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni'
        MANIFEST_BRANCH:
          description: 'Specify your Manifest Branch'
          required: true
          default: 'twrp-8.1'
        DEVICE_TREE_URL:
          description: 'Device Tree URL'
          required: true
          default: 'https://github.com/BiraruStudios/android_device_infinix_X650'
        DEVICE_TREE_BRANCH:
          description: 'Specify your Device Tree Branch'
          required: true
          default: 'test'
        DEVICE_PATH:
          description: 'Specify your Device Path'
          required: true
          default: 'device/infinix/Infinix_X650'
        COMMON_TREE_URL:
          description: 'Common Tree URL (if no common tree, leave blank)'
          required: false
        COMMON_PATH:
          description: 'Common Path (if no common tree, leave blank)'
          required: false
        DEVICE_NAME:
          description: 'Specify your Device Name'
          required: true
          default: 'Infinix_X650'
        MAKEFILE_NAME:
          description: 'Specify your Makefile Name'
          required: true
          default: 'omni_Infinix_X650'
        BUILD_TARGET:
          description: 'Specify your Build Target'
          required: true
          default: 'recovery'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Initialize repo
        run: |
          mkdir workspace
          cd workspace
          echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
        id: pwd

      - name: Clone device tree
        run: |
          mkdir -p archive
          git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}
          git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} archive/
        working-directory: ${{ steps.pwd.outputs.workspace-folder }}

      - name: Verify git status
        run: |
          git log -1 --oneline
          git rev-parse HEAD
        working-directory: ${{ steps.pwd.outputs.workspace-folder }}/${{ github.event.inputs.DEVICE_PATH }}

      - name: Get Device Tree Commit Hash
        run: |
          git rev-parse HEAD > ${{ github.workspace }}/workspace/device_tree_commit.txt
        working-directory: ${{ steps.pwd.outputs.workspace-folder }}/${{ github.event.inputs.DEVICE_PATH }}
        id: get_device_tree_commit

      - name: Echo and LS
        run: |
          cat ${{ github.workspace }}/workspace/device_tree_commit.txt
          echo "[commit](${{ github.event.inputs.DEVICE_TREE_URL }}/commit/$(cat ${{ github.workspace }}/workspace/device_tree_commit.txt))"
